services:
  ari5123-ai-trader-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: owengauci24/ari5123-ai-trader-app:latest
    container_name: ari5123-ai-trader-app-container
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: /bin/bash -c "streamlit run ./src/main.py --server.port=8506"
    ports:
      - 8506:8506
    restart: unless-stopped
    volumes:
      - .:/ari5123-ai-trader-app